site_name: "Cours de Première NSI"
site_url: https://ferney-nsi.gitlab.io/premiere
repo_url: https://gitlab.com/ferney-nsi/premiere
edit_uri: tree/main/docs/
site_description: Cours d'informatique de Vincent BOUILLOT, Lycée International Ferney-Voltaire 
copyright: |
  Copyleft &#127279 2021 <a href="mailto:prof-bouillot@protonmail.com?subject=Questions sur le cours" target="_blank" rel="noopener">Vincent BOUILLOT</a>
docs_dir: docs

nav:
  - "Bienvenue": index.md
  - "Langage Python" :
    - "Variables" : python1.md
    - "Conditionnelles" : python2.md
    - "Boucles" : python3.md
    - "Fonctions" : python4.md
    - "Tableaux et tuples" : python5.md
    - "Modularité" : python6.md
    - "Dictionnaires" : python7.md
  - "TP" :
    - "Accueil TP" : index_tp.md
    - "TP 3" : tp3.md  
    - "TP 4" : tp4.md  
    - "TP 8" : tp8.md  
    - "TP 10" : tp10.md  
    - "TP 11" : tp11.md  
    - "TP 12" : tp12.md  
    - "TP 13" : tp13.md  
  - "Algorithmique" : 
    - "Algorithme de recherche" : algorithmes1.md
    - "Algorithme de tri 1" : algorithmes2.md
    - "Algorithme de tri 2" : algorithmes3.md
    - "Exercices de complexité" : complexity.md
  - "Extension" :
    - "GUI" : gui.md  
  - "Hack" :
    - "Clavier" : hack1.md
    - "Constantes" : pi.md
  - "Tables" :
    - "Fichiers utiles" : tables.md
  # - "Bac à sable" :  
    # - "Bac à sable" : sandbox.md
  #   - "Algorithmes de tri" : algorithmes2.md
  #   - "Algorithmes avancés" : algorithmes3.md
  # - "Représentation des données" :
  #   - "" : repr1.md
  #   - "" : repr2.md
  # - "Architecture machine": 
  #   - "Électronique et logique booléenne" : architecture1.md
  #   - "Architecture de Von Neumann" : architecture2.md
  - "Projets" :
    - "Conjecture de Goldbach" : projet1.md
    - "La plante fractale" : projet2.md 
    - "Bitcoin" : projet3.md
    - "Nombres flottants" : projet4.md 
    - "Création d'une rue" : projet5.md 
    - "Créez votre Bitcoin" : projet6.md
    - "pi, nombre univers ?" : projet7.md
  - "Systèmes d'exploitation" :
    - "OS" : os.md

theme:
    name: material
    custom_dir: my_theme_customizations/
    font: false                     # RGPD ; pas de fonte Google
    language: fr                    # français
    palette:                        # Palettes de couleurs jour/nuit
      - media: "(prefers-color-scheme: dark)"
        scheme: slate
        primary: blue
        accent: blue
        toggle:
            icon: material/weather-night
            name: Passer au mode jour
      - media: "(prefers-color-scheme: light)"
        scheme: default
        primary: indigo
        accent: indigo
        toggle:
            icon: material/weather-sunny
            name: Passer au mode nuit
    features:
        - navigation.instant
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.sections
        - navigation.expand
        - navigation.top
        - toc.integrate
        - header.autohide
    icon: 
        # logo: material/remote-desktop
        logo : fontawesome/solid/laptop-code
    # favicon: assets/images/favicon.png


markdown_extensions:
    - meta
    - abbr
    - def_list                      # Les listes de définition.
    - attr_list                     # Un peu de CSS et des attributs HTML.
    - footnotes                     # Notes[^1] de bas de page.  [^1]: ma note.
    - admonition                    # Blocs colorés  !!! info "ma remarque"
    - pymdownx.details              #   qui peuvent se plier/déplier.
    - pymdownx.caret                # Passage ^^souligné^^ ou en ^exposant^.
    - pymdownx.mark                 # Passage ==surligné==.
    - pymdownx.tilde                # Passage ~~barré~~ ou en ~indice~.
    - pymdownx.highlight            # Coloration syntaxique du code
    - pymdownx.inlinehilite         # pour  `#!python  <python en ligne>`
    - pymdownx.snippets             # Inclusion de fichiers externe.
    - pymdownx.tasklist:            # Cases à cocher  - [ ]  et - [x]
        custom_checkbox:    false   #   avec cases d'origine
        clickable_checkbox: true    #   et cliquables.
    - pymdownx.tabbed:               # Volets glissants.  === "Mon volet"
        alternate_style: true 
    - pymdownx.superfences:          # Imbrication de blocs.
        preserve_tabs: true
        custom_fences:
            - name: mermaid
              class: mermaid
              format: !!python/name:mermaid2.fence_mermaid
    - pymdownx.keys:                # Touches du clavier.  ++ctrl+d++
        separator: "\uff0b"
    - pymdownx.emoji:               # Émojis  :boom:
        emoji_index:     !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.tasklist:
        custom_checkbox: true
        clickable_checkbox: true
    - pymdownx.arithmatex:
        generic: true
    - toc:
        permalink: ⚓︎
        toc_depth: 3

extra:
    social:
        # - icon: fontawesome/brands/gitlab
        #   link: https://gitlab.com/ens-fr
        #   name: Enseignement en français

        - icon: fontawesome/brands/discourse
          link: https://mooc-forums.inria.fr/moocnsi/
          name: Le forum des enseignants de NSI

        - icon: fontawesome/brands/linux
          link: https://linuxfr.org/
          name: Promouvoir les Logiciels libres

        - icon: fontawesome/brands/wikipedia-w
          link: https://fr.wikipedia.org
          name: L'encyclopédie libre que chacun peut améliorer

        - icon: fontawesome/solid/paper-plane
          link: mailto:prof-bouillot@protonmail.com
          name: Écrire à l'auteur
    site_url: https://www.gitlab.com/bouillotvincent/


plugins:
  - search
  - macros
  - enumerate-headings
  - mermaid2:
      arguments:
          theme: 'dark'
            # ^(window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches) ? 'dark' : 'light'

extra_javascript:
  - xtra/javascripts/mathjax-config.js                    # MathJax
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - xtra/javascripts/interpreter.js
  - https://unpkg.com/mermaid/dist/mermaid.min.js
  - javascripts/numworks.js
  # - javascripts/mermaid.js
  # - javascripts/loader.js

extra_css:
  - xtra/stylesheets/pyoditeur.css
  - xtra/stylesheets/ajustements.css                      # ajustements
